name: 'Dockerfile tests'
description: 'Manually run pytest inside Dockerfile'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'nothing'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.who-to-greet }}
